name: MakerSpace Managment System (MMS)
url: https://makermanagement.github.io/
description: A inventory system for makerspaces

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
