name: MakerSpace Managment System (MMS)
url: https://makermanagement.github.io/
description: A inventory system for makerspaces

permalink: /:year/:month/:day/:title/
paginate: 10

future: true

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

authors:
  thomas:
    display_name: Thomas M. Bergby
    gravatar: 9ca01558224b33d8951bb31cdeef2940
    email: thomas.bergby@gmail.com
    web: bergby.net
    github: Thobber94
  nicolai:
    display_name: Nicolai Naglestad
    email:
    web:
    github:
  espen:
    display_name: Espen O. Skjeggestad
